# Site settings
title: Tadeu Zagallo
email: tadeuzagallo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    I am a happy coder, front-end lover and low level stuff enthusiast
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://tadeuzagallo.com" # the base hostname & protocol for your site
twitter_username: tadeuzagallo
github_username:  tadeuzagallo

# Build settings
markdown: kramdown
